DROP TRIGGER TR_USER_PROFILE_DUTY_INSERT ON USER_PROFILE_DUTY;
DROP FUNCTION USER_PROFILE_DUTY_INSERT();
DROP SEQUENCE S_USER_PROFILE_DUTY_ID;
DROP TABLE USER_PROFILE_DUTY;

DROP TRIGGER TR_USER_PROFILE_SECTION_INSERT ON USER_PROFILE_SECTION;
DROP FUNCTION USER_PROFILE_SECTION_INSERT();
DROP SEQUENCE S_USER_PROFILE_SECTION_ID;
DROP TABLE USER_PROFILE_SECTION;

DROP TRIGGER TR_USER_PROFILE_INSERT ON USER_PROFILE;
DROP FUNCTION USER_PROFILE_INSERT();
DROP SEQUENCE S_USER_PROFILE_ID;
DROP TABLE USER_PROFILE;

DROP TABLE DUTY;
DROP TABLE SECTION;
