CREATE TABLE DUTY (
  DUTY_CODE TEXT PRIMARY KEY,
  DUTY_NAME TEXT,
  BEGIN_DATE DATE,
  END_DATE DATE,
  CREATED_ON DATE DEFAULT CURRENT_DATE NOT NULL,
  CREATED_BY TEXT
);

CREATE TABLE USER_PROFILE (
  USER_PROFILE_ID INT PRIMARY KEY,
  FIRST_NAME TEXT,
  LAST_NAME TEXT,
  EMAIL TEXT,
  PHONE INT,
  CREATED_ON DATE,
  CREATED_BY TEXT
);

CREATE SEQUENCE S_USER_PROFILE_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1;

CREATE FUNCTION USER_PROFILE_INSERT()
  RETURNS TRIGGER AS
$BODY$
  BEGIN
    IF NEW.USER_PROFILE_ID IS NULL THEN
      SELECT NEXTVAL(S_USER_PROFILE_ID) INTO NEW.USER_PROFILE_ID FROM DUAL;
    END IF;
  END;
$BODY$
  LANGUAGE plpgsql VOLATILE COST 100
;

CREATE TRIGGER TR_USER_PROFILE_INSERT
  BEFORE INSERT ON USER_PROFILE FOR EACH ROW
    EXECUTE PROCEDURE USER_PROFILE_INSERT();

CREATE TABLE USER_PROFILE_DUTY (
  USER_DUTY_ID INT PRIMARY KEY,
  DUTY_CODE TEXT REFERENCES DUTY(DUTY_CODE),
  USER_PROFILE_ID INT REFERENCES USER_PROFILE(USER_PROFILE_ID),
  DUTY_DATE DATE
);

CREATE SEQUENCE S_USER_PROFILE_DUTY_ID MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1;

CREATE FUNCTION USER_PROFILE_DUTY_INSERT()
  RETURNS TRIGGER AS
$BODY$
  BEGIN
    IF NEW.USER_PROFILE_DUTY_ID IS NULL THEN
      SELECT NEXTVAL(S_USER_PROFILE_DUTY_ID) INTO NEW.USER_PROFILE_DUTY_ID FROM DUAL;
    END IF;
  END;
$BODY$
  LANGUAGE plpgsql VOLATILE COST 100
;

CREATE TRIGGER TR_USER_PROFILE_DUTY_INSERT
  BEFORE INSERT ON USER_PROFILE_DUTY FOR EACH ROW
    EXECUTE PROCEDURE USER_PROFILE_DUTY_INSERT();

CREATE TABLE SECTION (
  SECTION_CODE TEXT PRIMARY KEY,
  SECTION_NAME TEXT,
  BEGIN_DATE DATE,
  END_DATE DATE,
  CREATED_ON DATE DEFAULT CURRENT_DATE,
  CREATED_BY TEXT
);

CREATE TABLE USER_PROFILE_SECTION (
  USER_PROFILE_GROUP_ID INT PRIMARY KEY,
  USER_PROFILE_ID INT REFERENCES USER_PROFILE(USER_PROFILE_ID),
  SECTION_CODE TEXT REFERENCES SECTION(SECTION_CODE)
);

--INITIAL DATA
INSERT INTO USER_PROFILE (FIRST_NAME, LAST_NAME, EMAIL, PHONE, CREATED_ON, CREATED_BY) VALUES ('Sam', 'Nadarajan', 'sam.nadarajan@gmail.com', '4236450220', current_date, 'SYSTEM');

INSERT into DUTY (DUTY_CODE, DUTY_NAME, BEGIN_DATE, END_DATE, CREATED_BY) VALUES ('AV_SOUND', 'Run Audio for Church', CURRENT_DATE, to_date('2999-12-31', 'YYYY-MM-DD'), 'SYSTEM');
INSERT into DUTY (DUTY_CODE, DUTY_NAME, BEGIN_DATE, END_DATE, CREATED_BY) VALUES ('AV_VIDEO', 'Run Streaming for Church', CURRENT_DATE, to_date('2999-12-31', 'YYYY-MM-DD'), 'SYSTEM');
INSERT into DUTY (DUTY_CODE, DUTY_NAME, BEGIN_DATE, END_DATE, CREATED_BY) VALUES ('PC', 'Platform Chairman', CURRENT_DATE, to_date('2999-12-31', 'YYYY-MM-DD'), 'SYSTEM');
INSERT into DUTY (DUTY_CODE, DUTY_NAME, BEGIN_DATE, END_DATE, CREATED_BY) VALUES ('USH', 'Usher', CURRENT_DATE, to_date('2999-12-31', 'YYYY-MM-DD'), 'SYSTEM');
INSERT into DUTY (DUTY_CODE, DUTY_NAME, BEGIN_DATE, END_DATE, CREATED_BY) VALUES ('CLS', 'Close up church', CURRENT_DATE, to_date('2999-12-31', 'YYYY-MM-DD'), 'SYSTEM');